# This workflow will build a Java project with Maven and Docker Hub

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
  DOCKER_REGISTRY: docker.io                  # set this to your Amazon ECR repository name
  DOCKER_REPOSITORY: caiocf/person-api-restfull      # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
  # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
  # containerDefinitions section of your task definition


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=image::$DOCKER_REPOSITORY:${GITHUB_REF#refs/heads/}"
          echo ${{ steps.extract_branch.outputs.image }}

      - name: Print
        shell: bash
        run: |
          echo ${{ steps.extract_branch.outputs.image }}

